"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 256  

  # Spot ----------------------------------
  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - front_left_hip_x
          - front_left_hip_y
          - front_left_knee
          - front_right_hip_x
          - front_right_hip_y
          - front_right_knee
          - rear_left_hip_x
          - rear_left_hip_y
          - rear_left_knee
          - rear_right_hip_x
          - rear_right_hip_y
          - rear_right_knee

      gains:
        front_left_hip_x  : {p: 600, i: 0.9, d: 20}
        front_left_hip_y  : {p: 600, i: 0.9, d: 20}
        front_left_knee   : {p: 600, i: 0.9, d: 20}
        front_right_hip_x : {p: 600, i: 0.9, d: 20}
        front_right_hip_y : {p: 600, i: 0.9, d: 20}
        front_right_knee  : {p: 600, i: 0.9, d: 20}
        rear_left_hip_x   : {p: 600, i: 0.9, d: 20}
        rear_left_hip_y   : {p: 600, i: 0.9, d: 20}
        rear_left_knee    : {p: 600, i: 0.9, d: 20}
        rear_right_hip_x  : {p: 600, i: 0.9, d: 20}
        rear_right_hip_y  : {p: 600, i: 0.9, d: 20}
        rear_right_knee   : {p: 600, i: 0.9, d: 20}


# Arm ----------------------------------
"z1_gazebo":
  Joint01_controller:
      type: unitree_legged_control/UnitreeJointController
      joint: joint1
      pid: {p: 300.0, i: 0.0, d: 5.0}

  Joint02_controller:
      type: unitree_legged_control/UnitreeJointController
      joint: joint2
      pid: {p: 300.0, i: 0.0, d: 5.0}

  Joint03_controller:
      type: unitree_legged_control/UnitreeJointController
      joint: joint3
      pid: {p: 300.0, i: 0.0, d: 5.0}

  Joint04_controller:
      type: unitree_legged_control/UnitreeJointController
      joint: joint4
      pid: {p: 300.0, i: 0.0, d: 5.0}

  Joint05_controller:
      type: unitree_legged_control/UnitreeJointController
      joint: joint5
      pid: {p: 300.0, i: 0.0, d: 5.0}

  Joint06_controller:
      type: unitree_legged_control/UnitreeJointController
      joint: joint6
      pid: {p: 300.0, i: 0.0, d: 5.0}

