<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:macro name="generic_stereo_camera" params="name parent *origin ros_topic cam_info_topic update_rate width height image_format hfov baseline focal_length">
    
  <!-- Stereo Camera -->
  <joint name="${name}_left_camera_frame_joint" type="fixed">
    <!-- optical frame collocated with tilting DOF -->
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="${name}_left_camera_frame"/>
  </joint>
  <link name="${name}_left_camera_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
         <mesh filename="package://hector_sensors_description/meshes/generic_stereo_camera/stereo_camera.dae"/>
      </geometry>
    </visual>
  </link>
  <joint name="${name}_left_camera_optical_frame_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.5708 0.0 -1.5708" />
    <parent link="${name}_left_camera_frame" />
    <child link="${name}_left_camera_optical_frame"/>
  </joint>
  <link name="${name}_left_camera_optical_frame"/>
  <gazebo reference="${name}_left_camera_frame">
    <sensor type="multicamera" name="stereo_camera">
      <!-- see MultiSenseSLPlugin.h for available modes -->
      <update_rate>${update_rate}</update_rate>
      <camera name="left">
        <horizontal_fov>${hfov}</horizontal_fov>
        <image>
          <width>${width}</width>
          <height>${height}</height>
          <format>${image_format}</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </camera>
      <camera name="right">
        <pose>0 ${-baseline} 0 0 0 0</pose>
        <horizontal_fov>${hfov}</horizontal_fov>
        <image>
          <width>${width}</width>
          <height>${height}</height>
          <format>${image_format}</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </camera>
      <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
        <cameraName>${name}</cameraName>
        <imageTopicName>${ros_topic}</imageTopicName>
        <cameraInfoTopicName>${cam_info_topic}</cameraInfoTopicName>
        <frameName>${name}_left_camera_optical_frame</frameName>
        <!--<rightFrameName>right_camera_optical_frame</rightFrameName>-->
        <hackBaseline>${baseline}</hackBaseline>
        <focalLength>${focal_length}</focalLength> <!-- image_width / (2*tan(hfov_radian /2)) -->
        <CxPrime>${width/2}</CxPrime>
        <Cx>${width/2}</Cx>
        <Cy>${height/2}</Cy>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>


  <joint name="${name}_right_camera_frame_joint" type="fixed">
    <origin xyz="0.0 ${-baseline} 0.0"/>
    <parent link="${name}_left_camera_frame"/>
    <child link="${name}_right_camera_frame"/>
  </joint>
  <link name="${name}_right_camera_frame">
  </link>
  <joint name="${name}_right_camera_optical_frame_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.5708 0.0 -1.5708" />
    <parent link="${name}_right_camera_frame" />
    <child link="${name}_right_camera_optical_frame"/>
  </joint>
  <link name="${name}_right_camera_optical_frame"/>
  
  </xacro:macro>

</robot>
